/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

import deepspace.DamageToUI;
import deepspace.NumericDamageToUI;
import deepspace.SpecificDamageToUI;

/**
 *
 * @author leandrofdez
 */
public class DamageView extends javax.swing.JPanel {

    /**
     * Creates new form DamageView
     */
    public DamageView() {
        initComponents();
    }
    
    void setDamage(DamageToUI damage){
        
        jPDamage.removeAll();
        
        if (damage==null) this.setVisible(false);
            
        else{
            
            if(damage instanceof NumericDamageToUI){
                
                NumericDamageView view = new NumericDamageView();
                view.setNumericDamage((NumericDamageToUI)damage);
                jPDamage.add(view);
            }
            
            else {
                SpecificDamageView view = new SpecificDamageView();
                view.setSpecificDamage((SpecificDamageToUI)damage);
                jPDamage.add(view);
                
            }

            repaint();
            revalidate();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPDamage = new javax.swing.JPanel();

        add(jPDamage);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPDamage;
    // End of variables declaration//GEN-END:variables
}
