all: practica

practica: generador generador-pvc voraz pvc1 pvc2 pvc3

generador: ./Generador/generador.cpp
	g++ -O2 ./Generador/generador.cpp -o generador

generador-pvc: ./Generador-pvc/generador-pvc.cpp
	g++ -O2 ./Generador-pvc/generador-pvc.cpp -o generador-pvc

voraz: ./Voraz/voraz.cpp
	g++ -O2 ./Voraz/voraz.cpp -o voraz

pvc1: ./Pvc1/pvc1.cpp
	g++ -O2 ./Pvc1/pvc1.cpp -o pvc1

pvc2: ./Pvc2/pvc2.cpp
	g++ -O2 ./Pvc2/pvc2.cpp -o pvc2

pvc3: ./Pvc3/pvc3.cpp
	g++ -O2 ./Pvc3/pvc3.cpp -o pvc3

