/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

import deepspace.EnemyToUI;
import deepspace.GameState;
import controller.Controller;

/**
 *
 * @author leandrofdez
 */
public class EnemyStarShipView extends javax.swing.JPanel {
    
    //Enemy Loot
    private LootView lootView;
    
    //Enemy Damage
    private DamageView damageView;

    /**
     * Creates new form EnemyStarshipView
     */
    public EnemyStarShipView() {
        initComponents();
        
        lootView= new LootView();
        damageView= new DamageView();
        
        jPEnemyLoot.add(lootView);
        jPEnemyDamage.add(damageView);
        
    }
    
    void setEnemy(EnemyToUI enemy){
        
        jLEnemyname.setText(enemy.getName());
        jLEnemyammoPower.setText(Float.toString(enemy.getAmmoPower()));
        jLEnemyshieldPower.setText(Float.toString(enemy.getShieldPower()));
        
        lootView.setLoot(enemy.getLoot());
        damageView.setDamage(enemy.getDamage());
        
        GameState gameState= Controller.getInstance().getState();
        
        if (gameState == GameState.INIT || gameState==GameState.BEFORECOMBAT){
            
            lootView.setVisible(false);
            damageView.setVisible(false);
        }
        
        else{
            
            lootView.setVisible(true);
            damageView.setVisible(true);
        }
        
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPEnemyLoot = new javax.swing.JPanel();
        jPEnemyDamage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLEnemyname = new javax.swing.JLabel();
        jLEnemyammoPower = new javax.swing.JLabel();
        jLEnemyshieldPower = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel5.setText("jLabel5");

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPEnemyLoot.setBorder(javax.swing.BorderFactory.createTitledBorder("Loot"));

        jPEnemyDamage.setBorder(javax.swing.BorderFactory.createTitledBorder("Loss"));

        jLabel2.setText("Name: ");

        jLabel3.setText("Ammo Power: ");

        jLabel4.setText("Shield Power: ");

        jLEnemyname.setText("jLabel6");

        jLEnemyammoPower.setText("jLabel7");

        jLEnemyshieldPower.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPEnemyLoot, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(jPEnemyDamage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21)
                        .addComponent(jLEnemyshieldPower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(68, 68, 68)
                        .addComponent(jLEnemyname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLEnemyammoPower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLEnemyname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLEnemyammoPower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLEnemyshieldPower))
                .addGap(16, 16, 16)
                .addComponent(jPEnemyLoot, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPEnemyDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLEnemyammoPower;
    private javax.swing.JLabel jLEnemyname;
    private javax.swing.JLabel jLEnemyshieldPower;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPEnemyDamage;
    private javax.swing.JPanel jPEnemyLoot;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
