/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;
import deepspace.LootToUI;

/**
 *
 * @author leandrofdez
 */
public class LootView extends javax.swing.JPanel {

    /**
     * Creates new form LootView
     */
    public LootView() {
        initComponents();
    }
    
    void setLoot(LootToUI loot){
        
        jLnWeapons.setText("Weapons: " + Integer.toString(loot.getnWeapons()));
        jLnShields.setText("Shields: " + Integer.toString( loot.getnShields()));
        jLnHangars.setText("Hangar Size: " + Integer.toString(loot.getnHangars()));
        jLnSupplies.setText("Fuel Units: " + Integer.toString(loot.getnSupplies()));
        jLnMedals.setText("Medals: " + Integer.toString(loot.getnMedals()));
        
        repaint();
        //revalidate(); //Este no estoy seguro
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLnWeapons = new javax.swing.JLabel();
        jLnShields = new javax.swing.JLabel();
        jLnHangars = new javax.swing.JLabel();
        jLnSupplies = new javax.swing.JLabel();
        jLnMedals = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLnWeapons.setText("Weapons: ");

        jLnShields.setText("Shields: ");

        jLnHangars.setText("Hangar Size: ");

        jLnSupplies.setText("Fuel Units: ");

        jLnMedals.setText("Medals: ");

        jLabel1.setText("Botín");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLnWeapons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLnShields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLnHangars, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLnSupplies, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jLnMedals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnWeapons)
                    .addComponent(jLnSupplies))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnShields)
                    .addComponent(jLnMedals))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLnHangars)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLnHangars;
    private javax.swing.JLabel jLnMedals;
    private javax.swing.JLabel jLnShields;
    private javax.swing.JLabel jLnSupplies;
    private javax.swing.JLabel jLnWeapons;
    // End of variables declaration//GEN-END:variables
}
