all: p4

p4: generador bt bb

generador: ./Generador/generador.cpp
	g++ -O2 ./Generador/generador.cpp -o ./generador

bt: ./BT/bt.cpp
	g++ -O2 ./BT/bt.cpp -o ./bt

bb: ./BB/bb.cpp
	g++ -O2 ./BB/bb.cpp -o ./bb

