all: practica

practica: generador especifico dyv

generador: ./Generador/generador.cpp
	g++ -O2 ./Generador/generador.cpp -o generador

especifico: ./Especifico/especifico.cpp
	g++ -O2 ./Especifico/especifico.cpp -o especifico

dyv: ./Dyv/dyv.cpp
	g++ -O2 ./Dyv/dyv.cpp -o dyv
